# Generated by Django 5.1.4 on 2025-01-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column1", models.CharField(max_length=255)),
                ("column2", models.IntegerField()),
            ],
        ),
    ]
