version: '3.9'
services:
  web:
    build: .
    container_name: django_subscriptions_web
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:14
    container_name: django_subscriptions_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions_db
    ports:
      - "5432:5432"
