# Generated by Django 4.2.19 on 2025-03-09 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                ("name", models.CharField(max_length=150)),
                ("txn_create_date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CC",
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name="payment",
            name="cc",
            field=models.ManyToManyField(to="payments.creditcard"),
        ),
    ]
